# Generated by Django 3.2 on 2022-09-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/company', verbose_name='Logo')),
                ('call_us', models.CharField(max_length=25, verbose_name='Call_Us')),
                ('email_us', models.EmailField(max_length=254, verbose_name='Email_Us')),
                ('fb_link', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('insta_link', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('twit_link', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('emails', models.TextField(blank=True, max_length=100, null=True, verbose_name='Emails')),
                ('numbers', models.TextField(blank=True, max_length=100, null=True, verbose_name='Numbers')),
                ('address', models.TextField(blank=True, max_length=100, null=True, verbose_name='Address')),
            ],
        ),
    ]
