# Generated by Django 3.2 on 2022-09-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_company_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True, verbose_name='Linkedin'),
        ),
    ]
