# Generated by Django 3.2 on 2022-08-31 12:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(default=1, upload_to='brands/', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='brands/', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_brand', to='products.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_category', to='products.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='product_images/', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='productimages',
            name='image',
            field=models.ImageField(default=1, upload_to='product_images/', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='products.product', verbose_name='Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='products.product', verbose_name='Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productreview',
            name='rate',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxLengthValidator(5), django.core.validators.MinLengthValidator(1)], verbose_name='Rate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productreview',
            name='review',
            field=models.CharField(default=1, max_length=500, verbose_name='Review'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to='auth.user', verbose_name='User'),
            preserve_default=False,
        ),
    ]
